### ISSUE TITLE
Search for the 'html' element

### ISSUE THREAD

**Issue by dizzyn** [julienw/dollardom#11]
Hi, I just want to ask you if it's right that he main element ('html') is not possible to find.

    $dom.get("html")

returns an empty aray

It's not a big deal, i just want to ask you.

Thank you for the great work

**Comment by julienw** [comment]
Right, we start at the root element and then try to find their children; because "html" is the root element we can't find it. I guess we could special case it :)

good catch !

**Comment by dizzyn** [comment]
thanks for the answer, I don't think it's necessary

FYI the $dom does a great job in a next generation of *Voice Of America* and *Radio Free Europe* CMS. (millions visitors in development and non-democracy countries)

 - https://en.wikipedia.org/wiki/Radio_Free_Europe/Radio_Liberty
 - https://en.wikipedia.org/wiki/Voice_of_America

**Comment by julienw** [comment]
Hey I'm glad, thanks for the feedback :)
