### ISSUE TITLE
Demo is broken in Chrome and newer IE

### ISSUE THREAD

**Issue by sebastianberns** [julienw/dollardom#7]
http://julienw.github.io/dollardom/examples/

Basically, because it links to an [offline file](https://raw.github.com/julienw/dollardom/master/$dom-with-animate.min.js).

**Comment by moay** [comment]
Broken again... ;-)

**Comment by julienw** [comment]
Are you sure ? This seems to work for me.

**Comment by moay** [comment]
Pretty sure... ;-)

Doesn't work in Chrome becaus of the mime type of `dollardom-animate.min.js`.

This is my console output:

    julienw.github.io/:1 - Refused to execute script from 'https://raw.github.com/julienw/dollardom/master/dollardom-animate.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
    examples.js:1 - Uncaught ReferenceError: $dom is not defined
    http://julienw.github.io/favicon.ico - Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by julienw** [comment]
OK; it works in Firefox, that's why I didn't see it.

I'll look how I can make it download with a right mime type in gh. If you have an idea I'm all ears :)

**Comment by julienw** [comment]
looks like I could use rawgit.com or host the js library on the gh-pages branch.
