### ISSUE TITLE
bower support?

### ISSUE THREAD

**Issue by hanthethanh** [julienw/dollardom#9]
Hi,

is it possible to have bower support so that I can install $dom by bower?

**Comment by julienw** [comment]
Shouldn't be too hard !

Feel free to provide a bower.json in a PR, otherwise I can have a look myself in a few days.

**Comment by julienw** [comment]
Fixed in 6b0136ae40a7c5e6df72e240972fe3546250d45c

Can you tell me if this looks good from your pov ?

**Comment by hanthethanh** [comment]
looks good to me. Thank you.
